require("config.settings")
require("lazy-nvim")

require("config.keymaps")
require("config.commands")
require("config.colors")
require("config.rooter")
require("config.lsp")
require("config.tools")
require("config.ensure_installed")
